apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
patches:
  - path: patch-upgrade-compat.yaml
    target:
      kind: HelmRelease
      name: cilium
  - path: patch-gateway-api.yaml
    target:
      kind: HelmRelease
      name: cilium
