{{- if not .Values.existingSecret }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "velotime.fullname" . }}
  labels:
    {{- include "velotime.labels" . | nindent 4 }}
stringData:
  CACHE_URI: {{ include "velotime.redisUri" .Values.cache | quote }}
  ConnectionStrings__cache: {{ include "velotime.connectionStringRedis" .Values.cache | quote }}
type: "Opaque"
{{- end }}