apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  interval: 1h
  path: ./config/crds/bases
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: external-secrets
  dependsOn:
    - name: external-secrets
  timeout: 5m
