apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/flux-instance.yaml
  - gateway-api-crds.yaml
  - cilium-kustomization.yaml
  - cert-manager-kustomization.yaml
  - cert-manager-issuer-kustomization.yaml
  - gateway-kustomization.yaml
  - external-dns-namespace-kustomization.yaml
  - external-dns-kustomization.yaml
  - external-secrets-kustomization.yaml
  - external-secrets-crds-kustomization.yaml
  - external-secrets-operator-kustomization.yaml
  - external-secrets-crs-kustomization.yaml
