apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velotime-module-facilities-api
  namespace: velotime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: velotime-module-facilities-api
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CACHE_PASSWORD: "{{ .CACHE_PASSWORD }}"
        CACHE_URI: "redis://{{ .CACHE_HOST }}:{{ .CACHE_PORT }}"
        VELOTIMEDB_PASSWORD: "{{ .VELOTIMEDB_PASSWORD }}"
        VELOTIMEDB_URI: "postgresql://{{ .VELOTIMEDB_USER }}:{{ .VELOTIMEDB_PASSWORD }}@{{ .VELOTIMEDB_HOST }}:{{ .VELOTIMEDB_PORT }}/velotimedb"
        ConnectionStrings__cache: "{{ .CACHE_HOST }}:{{ .CACHE_PORT }},password={{ .CACHE_PASSWORD }}"
        ConnectionStrings__velotimedb: "Host={{ .VELOTIMEDB_HOST }};port={{ .VELOTIMEDB_PORT }};Username={{ .VELOTIMEDB_USER }};Password={{ .VELOTIMEDB_PASSWORD }};Database=velotimedb"
  data:
    - secretKey: CACHE_HOST
      remoteRef:
        key: velotime-cache-host
    - secretKey: CACHE_PORT
      remoteRef:
        key: velotime-cache-port
    - secretKey: CACHE_PASSWORD
      remoteRef:
        key: velotime-cache-password
    - secretKey: VELOTIMEDB_HOST
      remoteRef:
        key: velotime-database-host
    - secretKey: VELOTIMEDB_PORT
      remoteRef:
        key: velotime-database-port
    - secretKey: VELOTIMEDB_USER
      remoteRef:
        key: velotime-database-user
    - secretKey: VELOTIMEDB_PASSWORD
      remoteRef:
        key: velotime-database-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velotime-module-statistics-api
  namespace: velotime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: velotime-module-statistics-api
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CACHE_PASSWORD: "{{ .CACHE_PASSWORD }}"
        CACHE_URI: "redis://{{ .CACHE_HOST }}:{{ .CACHE_PORT }}"
        VELOTIMEDB_PASSWORD: "{{ .VELOTIMEDB_PASSWORD }}"
        VELOTIMEDB_URI: "postgresql://{{ .VELOTIMEDB_USER }}:{{ .VELOTIMEDB_PASSWORD }}@{{ .VELOTIMEDB_HOST }}:{{ .VELOTIMEDB_PORT }}/velotimedb"
        ConnectionStrings__cache: "{{ .CACHE_HOST }}:{{ .CACHE_PORT }},password={{ .CACHE_PASSWORD }}"
        ConnectionStrings__velotimedb: "Host={{ .VELOTIMEDB_HOST }};port={{ .VELOTIMEDB_PORT }};Username={{ .VELOTIMEDB_USER }};Password={{ .VELOTIMEDB_PASSWORD }};Database=velotimedb"
  data:
    - secretKey: CACHE_HOST
      remoteRef:
        key: velotime-cache-host
    - secretKey: CACHE_PORT
      remoteRef:
        key: velotime-cache-port
    - secretKey: CACHE_PASSWORD
      remoteRef:
        key: velotime-cache-password
    - secretKey: VELOTIMEDB_HOST
      remoteRef:
        key: velotime-database-host
    - secretKey: VELOTIMEDB_PORT
      remoteRef:
        key: velotime-database-port
    - secretKey: VELOTIMEDB_USER
      remoteRef:
        key: velotime-database-user
    - secretKey: VELOTIMEDB_PASSWORD
      remoteRef:
        key: velotime-database-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velotime-module-statistics-processor
  namespace: velotime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: velotime-module-statistics-processor
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CACHE_PASSWORD: "{{ .CACHE_PASSWORD }}"
        CACHE_URI: "redis://{{ .CACHE_HOST }}:{{ .CACHE_PORT }}"
        VELOTIMEDB_PASSWORD: "{{ .VELOTIMEDB_PASSWORD }}"
        VELOTIMEDB_URI: "postgresql://{{ .VELOTIMEDB_USER }}:{{ .VELOTIMEDB_PASSWORD }}@{{ .VELOTIMEDB_HOST }}:{{ .VELOTIMEDB_PORT }}/velotimedb"
        ConnectionStrings__cache: "{{ .CACHE_HOST }}:{{ .CACHE_PORT }},password={{ .CACHE_PASSWORD }}"
        ConnectionStrings__velotimedb: "Host={{ .VELOTIMEDB_HOST }};port={{ .VELOTIMEDB_PORT }};Username={{ .VELOTIMEDB_USER }};Password={{ .VELOTIMEDB_PASSWORD }};Database=velotimedb"
        ConnectionStrings__MessageBus: "{{ .ConnectionStrings__MessageBus }}"
  data:
    - secretKey: CACHE_HOST
      remoteRef:
        key: velotime-cache-host
    - secretKey: CACHE_PORT
      remoteRef:
        key: velotime-cache-port
    - secretKey: CACHE_PASSWORD
      remoteRef:
        key: velotime-cache-password
    - secretKey: VELOTIMEDB_HOST
      remoteRef:
        key: velotime-database-host
    - secretKey: VELOTIMEDB_PORT
      remoteRef:
        key: velotime-database-port
    - secretKey: VELOTIMEDB_USER
      remoteRef:
        key: velotime-database-user
    - secretKey: VELOTIMEDB_PASSWORD
      remoteRef:
        key: velotime-database-password
    - secretKey: ConnectionStrings__MessageBus
      remoteRef:
        key: velotime-messagebus
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velotime-module-timing-api
  namespace: velotime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: velotime-module-timing-api
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CACHE_PASSWORD: "{{ .CACHE_PASSWORD }}"
        CACHE_URI: "redis://{{ .CACHE_HOST }}:{{ .CACHE_PORT }}"
        VELOTIMEDB_PASSWORD: "{{ .VELOTIMEDB_PASSWORD }}"
        VELOTIMEDB_URI: "postgresql://{{ .VELOTIMEDB_USER }}:{{ .VELOTIMEDB_PASSWORD }}@{{ .VELOTIMEDB_HOST }}:{{ .VELOTIMEDB_PORT }}/velotimedb"
        ConnectionStrings__cache: "{{ .CACHE_HOST }}:{{ .CACHE_PORT }},password={{ .CACHE_PASSWORD }}"
        ConnectionStrings__velotimedb: "Host={{ .VELOTIMEDB_HOST }};port={{ .VELOTIMEDB_PORT }};Username={{ .VELOTIMEDB_USER }};Password={{ .VELOTIMEDB_PASSWORD }};Database=velotimedb"
  data:
    - secretKey: CACHE_HOST
      remoteRef:
        key: velotime-cache-host
    - secretKey: CACHE_PORT
      remoteRef:
        key: velotime-cache-port
    - secretKey: CACHE_PASSWORD
      remoteRef:
        key: velotime-cache-password
    - secretKey: VELOTIMEDB_HOST
      remoteRef:
        key: velotime-database-host
    - secretKey: VELOTIMEDB_PORT
      remoteRef:
        key: velotime-database-port
    - secretKey: VELOTIMEDB_USER
      remoteRef:
        key: velotime-database-user
    - secretKey: VELOTIMEDB_PASSWORD
      remoteRef:
        key: velotime-database-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velotime-module-timing-processor
  namespace: velotime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: velotime-module-timing-processor
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CACHE_PASSWORD: "{{ .CACHE_PASSWORD }}"
        CACHE_URI: "redis://{{ .CACHE_HOST }}:{{ .CACHE_PORT }}"
        VELOTIMEDB_PASSWORD: "{{ .VELOTIMEDB_PASSWORD }}"
        VELOTIMEDB_URI: "postgresql://{{ .VELOTIMEDB_USER }}:{{ .VELOTIMEDB_PASSWORD }}@{{ .VELOTIMEDB_HOST }}:{{ .VELOTIMEDB_PORT }}/velotimedb"
        ConnectionStrings__cache: "{{ .CACHE_HOST }}:{{ .CACHE_PORT }},password={{ .CACHE_PASSWORD }}"
        ConnectionStrings__velotimedb: "Host={{ .VELOTIMEDB_HOST }};port={{ .VELOTIMEDB_PORT }};Username={{ .VELOTIMEDB_USER }};Password={{ .VELOTIMEDB_PASSWORD }};Database=velotimedb"
        ConnectionStrings__MessageBus: "{{ .ConnectionStrings__MessageBus }}"
  data:
    - secretKey: CACHE_HOST
      remoteRef:
        key: velotime-cache-host
    - secretKey: CACHE_PORT
      remoteRef:
        key: velotime-cache-port
    - secretKey: CACHE_PASSWORD
      remoteRef:
        key: velotime-cache-password
    - secretKey: VELOTIMEDB_HOST
      remoteRef:
        key: velotime-database-host
    - secretKey: VELOTIMEDB_PORT
      remoteRef:
        key: velotime-database-port
    - secretKey: VELOTIMEDB_USER
      remoteRef:
        key: velotime-database-user
    - secretKey: VELOTIMEDB_PASSWORD
      remoteRef:
        key: velotime-database-password
    - secretKey: ConnectionStrings__MessageBus
      remoteRef:
        key: velotime-messagebus
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velotime-webui
  namespace: velotime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: velotime-webui
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CACHE_URI: "redis://{{ .CACHE_HOST }}:{{ .CACHE_PORT }}"
        ConnectionStrings__cache: "{{ .CACHE_HOST }}:{{ .CACHE_PORT }},password={{ .CACHE_PASSWORD }}"
  data:
    - secretKey: CACHE_HOST
      remoteRef:
        key: velotime-cache-host
    - secretKey: CACHE_PORT
      remoteRef:
        key: velotime-cache-port
    - secretKey: CACHE_PASSWORD
      remoteRef:
        key: velotime-cache-password