{{- if not .Values.existingSecret }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "velotime.fullname" . }}
  labels:
    {{- include "velotime.labels" . | nindent 4 }}
stringData:
  CACHE_PASSWORD: {{ .Values.cache.password }}
  CACHE_URI: {{ include "velotime.redisUri" .Values.cache | quote }}
  VELOTIMEDB_PASSWORD: {{ .Values.database.password }}
  VELOTIMEDB_URI: {{ include "velotime.databaseUri" .Values.database | quote }}
  ConnectionStrings__cache: {{ include "velotime.connectionStringRedis" .Values.cache | quote }}
  ConnectionStrings__velotimedb: {{ include "velotime.connectionStringPostgres" .Values.database | quote }}
  ConnectionStrings__MessageBus: "{{ .Values.secrets.MessageBus }}"
type: "Opaque"
{{- end }}