apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velotime-db-secret
  namespace: velotime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: velotime-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        host: "{{ .host }}"
        port: "{{ .port }}"
        database: velotimedb
        username: "{{ .username }}"
  data:
    - secretKey: host
      remoteRef:
        key: velotime-database-host
    - secretKey: port
      remoteRef:
        key: velotime-database-port
    - secretKey: username
      remoteRef:
        key: velotime-database-user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velotime-db-admin-secret
  namespace: velotime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: velotime-db-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        database: "{{ .database }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: database
      remoteRef:
        key: velotime-database-admin-database
    - secretKey: username
      remoteRef:
        key: velotime-database-admin-user
    - secretKey: password
      remoteRef:
        key: velotime-database-admin-password
