apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        host: "{{ .host }}"
        port: "{{ .port }}"
        database: "{{ .database }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: host
      remoteRef:
        key: keycloak-database-host
    - secretKey: port
      remoteRef:
        key: keycloak-database-port
    - secretKey: database
      remoteRef:
        key: keycloak-database-name
    - secretKey: username
      remoteRef:
        key: keycloak-database-user
    - secretKey: password
      remoteRef:
        key: keycloak-database-password
