name: "OpenTofu Format"

on:
  pull_request:
    branches:
      - main
      - production
    paths:
      - terraform/**

permissions:
  contents: read

jobs:
  format:
    name: "OpenTofu Format Check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version: "1.12.5"

      - name: OpenTofu Format Check
        run: tofu -chdir=terraform fmt -check

      - name: OpenTofu Format Check (flux-bootstrap)
        run: tofu -chdir=flux-bootstrap fmt -check
