apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-admin-secret
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: keycloak-db-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        database: "{{ .database }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: database
      remoteRef:
        key: keycloak-database-admin-database
    - secretKey: username
      remoteRef:
        key: keycloak-database-admin-user
    - secretKey: password
      remoteRef:
        key: keycloak-database-admin-password
